apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-agent
data:
  config.hcl: |
    "auto_auth" = {
      "method" = {
        "config" = {
          "role" = "secret-reader"

          "token_path" = "/var/run/secrets/kubernetes.io/serviceaccount/token"
        }

        "mount_path" = "auth/kubernetes"

        "type" = "kubernetes"
      }



      "sink" = {
        "config" = {
          "path" = "/home/vault/.vault-token"
        }

        "type" = "file"
      }
    }

    api_proxy {
      use_auto_auth_token = "force"
    }

    listener "tcp" {
        address = "127.0.0.1:8200"
        tls_disable = true
    }


    "exit_after_auth" = false

    "pid_file" = "/home/vault/.pid"

    "template" = {
      "contents" = "{{ with secret \"/secret/data/api_key\" }}{{ range $k, $v := .Data }}{{ $k }}: {{ $v }}\n{{ end }}{{ end }}"

      "destination" = "/vault/secrets/api_key"

      "left_delimiter" = "{{"

      "right_delimiter" = "}}"
    }

    "template_config" = {
      "exit_on_retry_failure" = true
    }

    "vault" = {
      "address" = "http://vault.default.svc:8200"
    }
