apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: btr-nginx-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: csi-hostpath-sc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: btr-nginx
spec:
  selector:
    matchLabels:
      app: btr-nginx
  template:
    metadata:
      labels:
        app: btr-nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        resources:
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-pv
          mountPath: /var/log/nginx
      volumes:
      - name: nginx-pv
        persistentVolumeClaim:
          claimName: btr-nginx-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: btr-nginx
spec:
  selector:
    app: btr-nginx
  ports:
  - port: 80
    targetPort: 80
  type: LoadBalancer
