---
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: btr-nginx-snapshot
spec:
  volumeSnapshotClassName: csi-hostpath-snapclass
  source:
    persistentVolumeClaimName: btr-nginx-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: btr-log-parser-logs
spec:
  storageClassName: csi-hostpath-sc
  dataSource:
    name: btr-nginx-snapshot
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: batch/v1
kind: Job
metadata:
  name: btr-log-parser
spec:
  template:
    spec:
      containers:
      - name: goaccess
        image: allinurl/goaccess:latest
        command:
          - sh
          - "-c"
          - "cat /logs/*.log | goaccess -o html --log-format COMBINED -"
        volumeMounts:
          - name: nginx-logs
            mountPath: /logs
      restartPolicy: Never
      volumes:
      - name: nginx-logs
        persistentVolumeClaim:
          claimName: btr-log-parser-logs
